### ISSUE TITLE
Diff Simulation Houdini Demo

### ISSUE THREAD

**Issue by jprnd** [taichi-dev/taichi_houdini#19]
Are there any demos you can share of a simple differentiable simulation implemented in houdini?

**Comment by YuCrazing** [comment]
Hi @jprnd , as far as I know, there is no auto-diff demos in houdini yet, what kind of specific physics simulation do you want to achieve?

**Comment by jprnd** [comment]
I am interested in topology optimization, training physics-informed neural networks, and augmenting reinforcement learning within Houdini and in real-time as co-design tools.

**Comment by YuCrazing** [comment]
I know your need more clearly now. At this stage, we are focused on developing more features of auto-diff itself. Thus, we won't consider providing more auto-diff x houdini examples recently.

As a result, I would suggest you writing standalone taichi programs (instead of writing in houdini) to learn auto-diff related examples.
